//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database_circusEntities : DbContext
    {
        private static Database_circusEntities _context;
        public Database_circusEntities()
            : base("name=Database_circusEntities")
        {
        }
    
        public static Database_circusEntities GetContext()
        {
            if (_context == null)
                _context = new Database_circusEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actor_circus> actor_circus { get; set; }
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<circus_program> circus_program { get; set; }
        public virtual DbSet<circus_troupe> circus_troupe { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Conductor> Conductor { get; set; }
        public virtual DbSet<Designer> Designer { get; set; }
        public virtual DbSet<Director> Director { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Job_title> Job_title { get; set; }
        public virtual DbSet<presentation> presentation { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tour_schedule> tour_schedule { get; set; }
        public virtual DbSet<type> type { get; set; }
        public virtual DbSet<Workers_circus> Workers_circus { get; set; }
        public virtual DbSet<Role> Role { get; set; }
    }
}
