//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour_schedule
    {
        public int Id_schedule { get; set; }
        public int presentation { get; set; }
        public System.DateTime data_start { get; set; }
        public System.DateTime data_end { get; set; }
        public string Place_spot { get; set; }
    
        public virtual presentation presentation1 { get; set; }
    }
}
